# Generated by Django 5.2.10 on 2026-03-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typeit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typingrecord',
            old_name='error',
            new_name='errors',
        ),
    ]
