# Generated by Django 5.2.10 on 2026-04-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeit', '0003_alter_typingrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingrecord',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
