# Generated by Django 5.2.10 on 2026-04-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeit', '0004_typingrecord_ai_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingrecord',
            name='original_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typingrecord',
            name='typed_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
